name: Java CI

on:
  - push
  - pull_request

defaults:
  run:
    working-directory: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup
        run: make setup

      - name: Build project
        run: make build

      - name: Checkstyle
        run: make checkstyleMain

      - name: Tests
        run: make test


